### ISSUE TITLE
Documentation for C#

### ISSUE THREAD

**Issue by fasteddys** [MikhailMCraft/JSONScript#1]
Hello I am trying to convert between a large set of JSON scemhas and C#, both ways (nested JSON).

I am unable to recover the nested JSON once its flattened, any chance we guidance there would be appreciated.
Do you have genereic factory object that can do the coversion on the fly between the two - for an adapter pattern.
Lastly, can you please add some C# samples and more help on how to apply this.

**Comment by mikhailmikhalchuk** [comment]
@fasteddys JSON provided for the program is formatted for the program only and is not meant for use anywhere else. Conversion from managed code to JSON would be aimless unless for use with another program that interprets the schemas the same way as this one does.

**Comment by Smug-B** [comment]
> @fasteddys JSON provided for the program is formatted for the program only and is not meant for use anywhere else. Conversion from managed code to JSON would be aimless unless for use with another program that interprets the schemas the same way as this one does.

@fasteddys, he's challenging you to do what he can't.
